apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos-deployment
  namespace: medisupply
  labels:
    app: productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productos
  template:
    metadata:
      labels:
        app: productos
    spec:
      containers:
      - name: productos
        image: 012146976167.dkr.ecr.us-east-2.amazonaws.com/productos:latest
        ports:
        - containerPort: 5008
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          export DATABASE_URL="postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/medisupply"
          python run.py
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
