apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-usuario-deployment
  namespace: medisupply
  labels:
    app: auth-usuario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-usuario
  template:
    metadata:
      labels:
        app: auth-usuario
    spec:
      containers:
      - name: auth-usuario
        image: 012146976167.dkr.ecr.us-east-2.amazonaws.com/auth-usuario:v2-amd64
        ports:
        - containerPort: 5001
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_USER
          value: "postgres"
        - name: DB_NAME
          value: "medisupply"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
