apiVersion: v1
kind: ConfigMap
metadata:
  name: mediador-web-configmap
  namespace: medisupply
data:
  AUTH_URL: "http://auth-usuario-service:5001"
  PROVEEDORES_URL: "http://proveedores-service:5006/api"
  VENDEDORES_URL: "http://vendedores-service:5007/v1"
  PRODUCTOS_URL: "http://productos-service:5008"
