apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedores-deployment
  namespace: medisupply
  labels:
    app: proveedores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proveedores
  template:
    metadata:
      labels:
        app: proveedores
    spec:
      containers:
      - name: proveedores
        image: 012146976167.dkr.ecr.us-east-2.amazonaws.com/proveedores:latest
        ports:
        - containerPort: 5006
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          export DATABASE_URL="postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/medisupply"
          python run.py
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
