name: Release Manual

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versión a publicar (ej: 1.0.1)'
        required: true
        default: '1.0.0'
  workflow_run:
    workflows:
      - "Deploy to AWS EKS"
      - "Test y cobertura para mediador-web"
      - "Test y cobertura para auth-usuario"
      - "Test y cobertura para productos_microservice"
      - "Test y cobertura para proveedores_microservice"
      - "Test y cobertura para producto-inventario-web"
      - "Test y cobertura para vendedores_microservice"
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Configurar Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Actualizar versión
        run: |
          echo "${{ github.event.inputs.version }}" > VERSION
          git add VERSION
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"


      - name: Forzar main igual a develop (reset hard)
        run: |
          git fetch origin
          git checkout main
          git reset --hard develop
          git push origin main --force

      - name: Push main y tag
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git push origin main
          git tag -a "v$VERSION" -m "Release $VERSION"
          git push origin "v$VERSION"

      - name: Crear Release en GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          release_name: "Release v${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
