name: Test y cobertura para producto-inventario-web

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'producto-inventario-web/**'

jobs:
  Test-producto-inventario-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: producto-inventario-web

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Ejecutar tests con cobertura
        run: |
          pytest --cov=. --cov-report=xml --cov-fail-under=80
