name: Test y cobertura para productos_microservice

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'productos_microservice/**'

jobs:
  Test-productos_microservice:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: productos_microservice

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Ejecutar tests con cobertura
        run: |
          pytest --cov=app --cov-report=xml --cov-fail-under=85
